name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get Latest Version
        id: latest-version
        uses: ./
        with:
          repository: nodes-app/latest-version-action

      - name: Output Latest Version
        run: |
          echo "Latest version: ${{ steps.latest-version.outputs.version }}"
